# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
